global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  # Métricas do próprio Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Métricas do Traefik
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']
    metrics_path: /metrics

  # Métricas da aplicação backend
  - job_name: 'clickhype-backend'
    static_configs:
      - targets: ['backend:3001']
    metrics_path: /api/v1/monitoring/metrics
    scrape_interval: 10s
    scrape_timeout: 5s

  # Métricas do PostgreSQL (via postgres_exporter se configurado)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Métricas do Redis (via redis_exporter se configurado)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Node Exporter para métricas do sistema (se configurado)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s 